"""Initial migration

Revision ID: 718578e34e85
Revises: 
Create Date: 2024-01-29 11:07:49.965439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718578e34e85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meme_api')
    # ### end Alembic commands ###
